rLogin - integrate into Tropykus
rsksmart/tropykus-app pull request #1
Opened 2021-09-03 05:10 UTC by lucachaco

![image](https://user-images.githubusercontent.com/85146/131953584-9290aabe-64b6-4115-bbe8-a85e053a2822.png)

![image](https://user-images.githubusercontent.com/85146/131953670-c13b6ecf-efc6-4762-acad-2db18dd88bed.png)

2021-09-06 04:09 UTC, ilanolkies requested changes
Excellent PR! Before sending I would also mark in this PR:
1. Why Portis is not integrated
2. How this was tested, explaining what we have commented out while developing
3. Some ref links to rLogin docs
4. Details about the implementation including the latest comment

2021-09-06 04:09 UTC, ilanolkies commented on src/store/modules/Session.js
> +const getAccounts = (provider) => providerRPC(provider, { method: 'eth_accounts' });
```suggestion
const getAccounts = (provider) => provider.request({ method: 'eth_accounts' });
```

2021-09-06 04:09 UTC, ilanolkies commented on src/components/menu/Navbar.vue
> +        .connect()
```suggestion
      this.rLogin
        .connect() // shows rLogin modal
```

2021-09-06 04:09 UTC, ilanolkies commented on src/store/modules/Session.js
> +  [constants.SESSION_CONNECT_WEB3]: async ({ commit, dispatch }, provider) => {
This is the most important part of the PR. All the responsibility of this part of the code was moved to rLogin. We must remark this when we do the PR.

We also have to make sure this action is not called from somewhere else since the parameter type has changed

2021-09-06 13:37 UTC, ilanolkies commented on package.json
> +    "@rsksmart/rlogin-web3-react-connector": "^1.0.1",
```suggestion
```

Not used here

2021-09-06 21:32 UTC, lucachaco commented on src/store/modules/Session.js
> +const getAccounts = (provider) => providerRPC(provider, { method: 'eth_accounts' });
Good catch, I dont know how I didnt see this

2021-09-07 01:32 UTC, lucachaco commented on src/store/modules/Session.js
>    });
This is not needed anymore since rLogin detects the network change: 
![image](https://user-images.githubusercontent.com/85146/132270888-39a0c475-e0c7-4540-9ee9-ccec61c92fef.png)

2021-09-07 01:38 UTC, lucachaco commented on src/store/modules/Session.js
> +  [constants.SESSION_CONNECT_WEB3]: async ({ commit, dispatch }, provider) => {
I updated all SESSION_CONNECT_WEB3 actions to make it compatible with rLoging

2021-09-07 09:48 UTC, jessgusclark commented
Hey @lucachaco, how do I test this locally? When I run it, I get a firebase error and a WebSockets error. Do I need to create a firebase project first?

2021-09-08 03:52 UTC, lucachaco commented
Hi @jessgusclark I had to remove all the call to firebase and websockets. Take a look here: https://github.com/rsksmart/tropykus-app/pull/2 
Sorry it is a bit messy but it was the only way to make it run. I tried asking them a firebase project but they said still for internal use only

2021-09-09 23:07 UTC, closed without merging